package PrimeApp;


/**
* PrimeApp/PrimePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Prime.idl
* Thursday, 25 May, 2023 9:59:07 PM IST
*/

public abstract class PrimePOA extends org.omg.PortableServer.Servant
 implements PrimeApp.PrimeOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("CheckPrime", new java.lang.Integer (0));
    _methods.put ("shutdown", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // PrimeApp/Prime/CheckPrime
       {
         int num = in.read_long ();
         String $result = null;
         $result = this.CheckPrime (num);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // PrimeApp/Prime/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:PrimeApp/Prime:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Prime _this() 
  {
    return PrimeHelper.narrow(
    super._this_object());
  }

  public Prime _this(org.omg.CORBA.ORB orb) 
  {
    return PrimeHelper.narrow(
    super._this_object(orb));
  }


} // class PrimePOA
