package PrimeApp;

/**
* PrimeApp/PrimeHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Prime.idl
* Thursday, 25 May, 2023 9:59:07 PM IST
*/

public final class PrimeHolder implements org.omg.CORBA.portable.Streamable
{
  public PrimeApp.Prime value = null;

  public PrimeHolder ()
  {
  }

  public PrimeHolder (PrimeApp.Prime initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = PrimeApp.PrimeHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    PrimeApp.PrimeHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return PrimeApp.PrimeHelper.type ();
  }

}
