package PrimeApp;


/**
* PrimeApp/Prime.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Prime.idl
* Thursday, 25 May, 2023 9:59:07 PM IST
*/

public interface Prime extends PrimeOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Prime
