package StringReverseApp;


/**
* StringReverseApp/StringReverseOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from StringReverse.idl
* Thursday, 25 May, 2023 5:37:49 AM IST
*/

public interface StringReverseOperations 
{
  String Reverse (String str1);
  void shutdown ();
} // interface StringReverseOperations
